// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  image: string;
  info: string;
  loading: string;
  noResults: string;
  overview: string;
  result: string;
  results: string;
  spinner: string;
  title: string;
  year: string;
}
export const cssExports: CssExports;
export default cssExports;
