// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  image: string;
  info: string;
  input: string;
  overview: string;
  result: string;
  results: string;
  title: string;
  year: string;
}
export const cssExports: CssExports;
export default cssExports;
