// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  isHigh: string;
  isLow: string;
  isMid: string;
  rating: string;
  ratingIcon: string;
}
export const cssExports: CssExports;
export default cssExports;
