// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  card: string;
  cardHeading: string;
  companies: string;
  companyLogo: string;
  container: string;
  country: string;
  genre: string;
  goHomeButton: string;
  image: string;
  imdbLogo: string;
  info: string;
  infoItem: string;
  infoTitle: string;
  infoValue: string;
  loading: string;
  notFound: string;
  overview: string;
  subtitle: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
