// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  adultIcon: string;
  container: string;
  image: string;
  info: string;
  overview: string;
  rating: string;
  title: string;
  year: string;
}
export const cssExports: CssExports;
export default cssExports;
