// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  heading: string;
  image: string;
  list: string;
  loading: string;
  movie: string;
  movieInfo: string;
  movieOverview: string;
  movieTitle: string;
  noResults: string;
  rating: string;
  title: string;
  year: string;
}
export const cssExports: CssExports;
export default cssExports;
